name: Checkout repo and list files

on:
  workflow_dispatch:   # manual trigger (Run workflow button)

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout a specific repository
        uses: actions/checkout@v4
        with:
          repository: TomerHanan/Rolling-Project-Terraform
          ref: main            # branch, tag, or commit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ls -la
        run: |
          ls -la
